export const LOAD_PAGES_REQUEST = 'LOAD_PAGES_REQUEST'
export const LOAD_PAGES_SUCCESS = 'LOAD_PAGES_SUCCESS'
export const LOAD_PAGES_FAILURE = 'LOAD_PAGES_FAILURE'

export const LOAD_PAGE_REQUEST = 'LOAD_PAGE_REQUEST'
export const LOAD_PAGE_SUCCESS = 'LOAD_PAGE_SUCCESS'
export const LOAD_PAGE_FAILURE = 'LOAD_PAGE_FAILURE'

export const CREATE_PAGE_REQUEST = 'CREATE_PAGE_REQUEST'
export const CREATE_PAGE_SUCCESS = 'CREATE_PAGE_SUCCESS'
export const CREATE_PAGE_FAILURE = 'CREATE_PAGE_FAILURE'

export const DELETE_PAGE_REQUEST = 'DELETE_PAGE_REQUEST'
export const DELETE_PAGE_SUCCESS = 'DELETE_PAGE_SUCCESS'
export const DELETE_PAGE_FAILURE = 'DELETE_PAGE_FAILURE'

export const UPDATE_PAGE_REQUEST = 'UPDATE_PAGE_REQUEST'
export const UPDATE_PAGE_SUCCESS = 'UPDATE_PAGE_SUCCESS'
export const UPDATE_PAGE_FAILURE = 'UPDATE_PAGE_FAILURE'


export const LOAD_USERS_REQUEST = 'LOAD_USERS_REQUEST'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAILURE = 'LOAD_USERS_FAILURE'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const LOAD_DATAS_REQUEST = 'LOAD_DATAS_REQUEST'
export const LOAD_DATAS_SUCCESS = 'LOAD_DATAS_SUCCESS'
export const LOAD_DATAS_FAILURE = 'LOAD_DATAS_FAILURE'

export const LOAD_DATA_REQUEST = 'LOAD_DATA_REQUEST'
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS'
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'

export const RECEIVE_PROTECTED_DATA='RECEIVE_PROTECTED_DATA'
export const FETCH_PROTECTED_DATA_REQUEST='FETCH_PROTECTED_DATA_REQUEST'

export const LOAD_ROOMSCOL_REQUEST='LOAD_ROOMSCOL_REQUEST'
export const LOAD_ROOMSCOL_SUCCESS='LOAD_ROOMSCOL_SUCCESS'
export const LOAD_ROOMSCOL_FAILURE='LOAD_ROOMSCOL_FAILURE'

export const CREATE_ROOMSCOL_REQUEST='CREATE_ROOMSCOL_REQUEST'
export const CREATE_ROOMSCOL_SUCCESS='CREATE_ROOMSCOL_SUCCESS'
export const CREATE_ROOMSCOL_FAILURE='CREATE_ROOMSCOL_FAILURE'
